import type { Signal } from '@/types';

export const mockSignals: Signal[] = [
  // ============================================
  // GCC MARKET LIQUIDITY SIGNALS (Dec 27, 2025 - Jan 3, 2026)
  // ============================================
  
  {
    id: 'gcc-makkah-realestate-2025',
    type: 'real_estate',
    severity: 'critical',
    title: 'Makkah Construction & Development Co. — SAR 980M Land Acquisition Cash-Out',
    description:
      'Major land parcel acquisition in Makkah Central District. Seller-side liquidity event creating immediate wealth extraction opportunity for long-term landholders. Transaction structured as cash-only deal with settlement within 15 days.',
    source: 'Argaam',
    createdAt: new Date('2025-12-27T09:30:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 980,
    confidence: 92,
    prospectId: 'gcc-prospect-001',
    prospectName: 'Al-Rashid Family Office',
    metadata: {
      signalType: 'Liquidity',
      status: 'Open',
      clientType: 'Family Office',
      assignedRM: 'Khalid Al-Mansour',
      liquidityAmount: 'SAR 980M',
      currency: 'SAR',
      region: 'Saudi Arabia',
      city: 'Makkah',
      dataSource: 'Argaam',
      keyDates: ['Transaction announced 27 Dec 2025', 'Settlement by 12 Jan 2026'],
      impactedClients: ['High net worth landholders', 'Family offices with real estate exposure'],
      window: '0–30 days (by 26 Jan 2026)',
    },
  },
  
  {
    id: 'gcc-catrion-akcc-2025',
    type: 'strategic_stake_sale',
    severity: 'high',
    title: 'Catrion Acquisition of 55% Stake in AKCC — SAR 441M Founder Partial Exit',
    description:
      'Strategic acquisition by Catrion of controlling stake in AKCC (Arabian Key Construction Co.). Founding family retaining 45% equity stake while realizing SAR 441M in immediate liquidity. Mixed cash-equity structure provides both wealth extraction and continued upside.',
    source: 'Zawya',
    createdAt: new Date('2025-12-28T11:15:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 441,
    confidence: 88,
    prospectId: 'gcc-prospect-002',
    prospectName: 'Ahmed Al-Khateeb (AKCC Founder)',
    metadata: {
      signalType: 'Liquidity',
      status: 'In Review',
      clientType: 'Founder-led',
      assignedRM: 'Fatima Al-Sayed',
      liquidityAmount: 'SAR 441M',
      currency: 'SAR',
      region: 'Saudi Arabia',
      city: 'Riyadh',
      dataSource: 'Zawya (LSEG)',
      keyDates: ['Deal announced 28 Dec 2025', 'Expected closing 20 Jan 2026'],
      impactedClients: ['AKCC founding shareholders', 'Construction sector founders'],
      window: '0–30 days (by 26 Jan 2026)',
      notes: 'Founders seeking wealth diversification while maintaining strategic control.',
    },
  },
  
  {
    id: 'gcc-aldyar-ipo-2025',
    type: 'ipo_approval',
    severity: 'high',
    title: 'Aldyar Alarabiya IPO Approval — 30% Free Float Pre-IPO Liquidity',
    description:
      'Capital Market Authority (CMA) approved Aldyar Alarabiya Real Estate IPO for 30% public float on Tadawul. Pre-IPO secondary transactions creating liquidity window for existing shareholders ahead of listing expected in Q1 2026.',
    source: 'Tadawul',
    createdAt: new Date('2025-12-29T08:45:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_60_days',
    estimatedLiquidity: 320,
    confidence: 85,
    prospectId: 'gcc-prospect-003',
    prospectName: 'Aldyar Existing Shareholders',
    metadata: {
      signalType: 'Wealth Creation',
      status: 'Open',
      clientType: 'UHNW',
      assignedRM: 'Mohammed Al-Qahtani',
      liquidityAmount: 'SAR 320M (estimated)',
      currency: 'SAR',
      region: 'Saudi Arabia',
      city: 'Jeddah',
      dataSource: 'Tadawul',
      keyDates: ['CMA approval 29 Dec 2025', 'IPO listing expected Feb 2026'],
      impactedClients: ['Pre-IPO shareholders', 'Real estate investors'],
      window: '30–60 days (27 Jan → 25 Feb 2026)',
      notes: 'Lock-in period of 6 months post-listing for founders.',
    },
  },
  
  {
    id: 'gcc-wareed-healthcare-2025',
    type: 'healthcare',
    severity: 'medium',
    title: 'Al Hammadi Acquisition of 40% Wareed Medical — USD 85M Healthcare Consolidation',
    description:
      'Al Hammadi Hospital Group acquiring 40% stake in Wareed Medical Services for USD 85M. Partial exit for founding physicians and early investors. Healthcare sector consolidation trend creating multiple exit opportunities across GCC.',
    source: 'SWFI',
    createdAt: new Date('2025-12-30T10:20:00Z'),
    isActioned: false,
    isRead: true,
    expectedTimeline: '30_days',
    estimatedLiquidity: 85,
    confidence: 81,
    prospectId: 'gcc-prospect-004',
    prospectName: 'Dr. Samir Al-Hashimi (Wareed Co-Founder)',
    metadata: {
      signalType: 'Liquidity',
      status: 'In Review',
      clientType: 'Founder-led',
      assignedRM: 'Layla Al-Mazrouei',
      liquidityAmount: 'USD 85M',
      currency: 'USD',
      region: 'UAE',
      city: 'Dubai',
      dataSource: 'SWFI',
      keyDates: ['Transaction signed 30 Dec 2025', 'Closing expected 25 Jan 2026'],
      impactedClients: ['Healthcare founders', 'Medical practice owners'],
      window: '0–30 days (by 26 Jan 2026)',
      notes: 'Part of broader GCC healthcare consolidation wave.',
    },
  },
  
  {
    id: 'gcc-energy-logistics-2025',
    type: 'energy',
    severity: 'critical',
    title: 'Saudi Energy Logistics IPO — SAR 1.2B Founder Pre-Listing Liquidity',
    description:
      'Saudi Energy Logistics Company (SELCO) approved for Tadawul listing with 25% free float. Founders executing secondary share sale ahead of IPO creating SAR 1.2B liquidity event. Strategic investors positioning for IPO gains.',
    source: 'CMA Saudi Arabia',
    createdAt: new Date('2025-12-31T07:00:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_60_days',
    estimatedLiquidity: 1200,
    confidence: 90,
    prospectId: 'gcc-prospect-005',
    prospectName: 'SELCO Founding Group',
    metadata: {
      signalType: 'Wealth Creation',
      status: 'Open',
      clientType: 'Founder-led',
      assignedRM: 'Omar Al-Faisal',
      liquidityAmount: 'SAR 1.2B',
      currency: 'SAR',
      region: 'Saudi Arabia',
      city: 'Dammam',
      dataSource: 'CMA Saudi Arabia',
      keyDates: ['CMA approval 31 Dec 2025', 'Listing expected late Feb 2026'],
      impactedClients: ['Energy sector founders', 'Logistics infrastructure investors'],
      window: '30–60 days (27 Jan → 25 Feb 2026)',
      notes: 'Saudi Vision 2030 infrastructure beneficiary.',
    },
  },
  
  {
    id: 'gcc-consumer-retail-2026',
    type: 'consumer',
    severity: 'medium',
    title: 'Majid Al Futtaim Investment in Gulf Gourmet — AED 195M Strategic Partnership',
    description:
      'Majid Al Futtaim (MAF) acquiring 35% stake in Gulf Gourmet food services for AED 195M. Founding family monetizing portion of stake while partnering with regional retail leader. Consumer sector consolidation creating wealth events.',
    source: 'DIFC',
    createdAt: new Date('2026-01-01T14:30:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 195,
    confidence: 83,
    prospectId: 'gcc-prospect-006',
    prospectName: 'Al-Nuaimi Family (Gulf Gourmet)',
    metadata: {
      signalType: 'Liquidity',
      status: 'Open',
      clientType: 'Family Office',
      assignedRM: 'Sara Al-Dhaheri',
      liquidityAmount: 'AED 195M',
      currency: 'AED',
      region: 'UAE',
      city: 'Dubai',
      dataSource: 'DIFC',
      keyDates: ['Partnership announced 1 Jan 2026', 'Closing by 30 Jan 2026'],
      impactedClients: ['Consumer sector founders', 'F&B business owners'],
      window: '0–30 days (by 26 Jan 2026)',
    },
  },
  
  {
    id: 'gcc-fintech-series-c-2026',
    type: 'financial_services',
    severity: 'high',
    title: 'PayTabs Series C — USD 110M Fintech Funding with Partial Founder Exit',
    description:
      'PayTabs securing USD 110M Series C led by regional sovereign wealth funds. Transaction includes USD 35M secondary component allowing founder and early employee liquidity. Fintech sector maturation creating exit opportunities.',
    source: 'SAMA',
    createdAt: new Date('2026-01-02T09:00:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 35,
    confidence: 87,
    prospectId: 'gcc-prospect-007',
    prospectName: 'Abdulaziz Al-Jouf (PayTabs Founder)',
    metadata: {
      signalType: 'Liquidity',
      status: 'Open',
      clientType: 'Founder-led',
      assignedRM: 'Khalid Al-Mansour',
      liquidityAmount: 'USD 35M (secondary)',
      currency: 'USD',
      region: 'Saudi Arabia',
      city: 'Riyadh',
      dataSource: 'SAMA',
      keyDates: ['Series C announced 2 Jan 2026', 'Closing expected 28 Jan 2026'],
      impactedClients: ['Fintech founders', 'Early employees with equity'],
      window: '0–30 days (by 26 Jan 2026)',
      notes: 'SAMA-licensed payment gateway with strong growth metrics.',
    },
  },
  
  {
    id: 'gcc-family-office-rotation-2026',
    type: 'family_office_rotation',
    severity: 'medium',
    title: 'Al-Rajhi Family Office Asset Rotation — SAR 450M Rebalancing Event',
    description:
      'Al-Rajhi Family Office executing strategic rebalancing, rotating SAR 450M from mature real estate holdings into technology and healthcare sectors. Multi-generational wealth repositioning creating liquidity and reinvestment flow.',
    source: 'Argaam',
    createdAt: new Date('2026-01-02T16:45:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_60_days',
    estimatedLiquidity: 450,
    confidence: 79,
    prospectId: 'gcc-prospect-008',
    prospectName: 'Al-Rajhi Family Office',
    metadata: {
      signalType: 'Liquidity',
      status: 'Open',
      clientType: 'Family Office',
      assignedRM: 'Fatima Al-Sayed',
      liquidityAmount: 'SAR 450M',
      currency: 'SAR',
      region: 'Saudi Arabia',
      city: 'Riyadh',
      dataSource: 'Argaam',
      keyDates: ['Rebalancing announced 2 Jan 2026', 'Execution window Jan-Feb 2026'],
      impactedClients: ['Multi-generational family offices', 'UHNW portfolio managers'],
      window: '30–60 days (27 Jan → 25 Feb 2026)',
      notes: 'Strategic shift toward Vision 2030 growth sectors.',
    },
  },
  
  {
    id: 'gcc-adx-developer-2026',
    type: 'real_estate',
    severity: 'high',
    title: 'Aldar Properties Secondary Offering — AED 820M Institutional Placement',
    description:
      'Aldar Properties executing AED 820M secondary placement via ADX for institutional investors. Existing shareholders including family offices offered liquidity window at premium to current trading price.',
    source: 'ADX',
    createdAt: new Date('2026-01-03T08:15:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 820,
    confidence: 91,
    prospectId: 'gcc-prospect-009',
    prospectName: 'Aldar Institutional Shareholders',
    metadata: {
      signalType: 'Liquidity',
      status: 'Open',
      clientType: 'UHNW',
      assignedRM: 'Mohammed Al-Qahtani',
      liquidityAmount: 'AED 820M',
      currency: 'AED',
      region: 'UAE',
      city: 'Abu Dhabi',
      dataSource: 'ADX',
      keyDates: ['Placement announced 3 Jan 2026', 'Book building 15-20 Jan 2026'],
      impactedClients: ['Real estate investors', 'Listed equity holders'],
      window: '0–30 days (by 26 Jan 2026)',
    },
  },
  
  {
    id: 'gcc-dfm-logistics-2026',
    type: 'logistics',
    severity: 'medium',
    title: 'Emirates Post Group Stake Sale — AED 125M Government Divestment Program',
    description:
      'UAE government divesting 20% stake in Emirates Post Group via DFM as part of broader privatization initiative. Creates liquidity opportunity for strategic buyers and institutional investors targeting logistics infrastructure.',
    source: 'DFM',
    createdAt: new Date('2026-01-03T11:30:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_60_days',
    estimatedLiquidity: 125,
    confidence: 84,
    prospectId: 'gcc-prospect-010',
    prospectName: 'Strategic Logistics Investors',
    metadata: {
      signalType: 'Wealth Creation',
      status: 'Open',
      clientType: 'UHNW',
      assignedRM: 'Layla Al-Mazrouei',
      liquidityAmount: 'AED 125M',
      currency: 'AED',
      region: 'UAE',
      city: 'Dubai',
      dataSource: 'DFM',
      keyDates: ['Divestment announced 3 Jan 2026', 'Transaction expected Feb 2026'],
      impactedClients: ['Infrastructure investors', 'Sovereign wealth funds'],
      window: '30–60 days (27 Jan → 25 Feb 2026)',
      notes: 'Part of UAE economic diversification strategy.',
    },
  },
  
  {
    id: 'gcc-adgm-hospitality-2026',
    type: 'acquisition',
    severity: 'high',
    title: 'Jumeirah Hotels Partial Exit — USD 290M Stake Sale to Global Hospitality Group',
    description:
      'Jumeirah Group divesting 30% stake to international hospitality operator for USD 290M. Dubai government-backed entity monetizing premium asset while maintaining strategic control. Hospitality sector M&A creating wealth events.',
    source: 'ADGM',
    createdAt: new Date('2026-01-03T13:00:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_60_days',
    estimatedLiquidity: 290,
    confidence: 86,
    prospectId: 'gcc-prospect-011',
    prospectName: 'Jumeirah Existing Stakeholders',
    metadata: {
      signalType: 'Liquidity',
      status: 'Open',
      clientType: 'UHNW',
      assignedRM: 'Omar Al-Faisal',
      liquidityAmount: 'USD 290M',
      currency: 'USD',
      region: 'UAE',
      city: 'Abu Dhabi',
      dataSource: 'ADGM',
      keyDates: ['Transaction announced 3 Jan 2026', 'Closing expected Feb-Mar 2026'],
      impactedClients: ['Hospitality sector investors', 'Tourism infrastructure stakeholders'],
      window: '30–60 days (27 Jan → 25 Feb 2026)',
      notes: 'Strategic partnership model with continued local ownership.',
    },
  },
  
  {
    id: 'gcc-tech-unicorn-2026',
    type: 'wealth_creation',
    severity: 'critical',
    title: 'Careem Co-Founders Secondary Transaction — USD 180M Liquidity via Uber Earnout',
    description:
      'Careem co-founders and early employees receiving USD 180M earnout payment as part of 2020 Uber acquisition milestones. Multi-year earnout structure creating sustained liquidity events for MENA tech pioneers.',
    source: 'Zawya',
    createdAt: new Date('2026-01-03T15:45:00Z'),
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 180,
    confidence: 93,
    prospectId: 'gcc-prospect-012',
    prospectName: 'Careem Early Stakeholders',
    metadata: {
      signalType: 'Wealth Creation',
      status: 'Closed',
      clientType: 'Founder-led',
      assignedRM: 'Sara Al-Dhaheri',
      liquidityAmount: 'USD 180M',
      currency: 'USD',
      region: 'UAE',
      city: 'Dubai',
      dataSource: 'Zawya (LSEG)',
      keyDates: ['Earnout milestone achieved 30 Dec 2025', 'Payment processed 3 Jan 2026'],
      impactedClients: ['Tech startup founders', 'Early-stage tech investors'],
      window: '0–30 days (completed)',
      notes: 'Largest tech exit milestone payment in MENA region for 2026.',
    },
  },
  
  // ============================================
  // EXISTING SIGNALS (maintained for continuity)
  // ============================================
  
  {
    id: 'nectar-buyback-2025',
    type: 'buyback',
    severity: 'high',
    title: 'Nectar Lifesciences — Buyback (record date liquidity)',
    description:
      'Record date on 24 Dec 2025 for the announced buyback; tender route provides cash-out for shareholders and often precedes block repositioning.',
    source: 'Bloomberg Gulf',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 150,
    confidence: 90,
    metadata: {
      keyDates: ['Record date 24 Dec 2025'],
      people: ['Company', 'Public shareholders'],
      signalType: 'Buyback / tender offer',
      window: '0–30 days (by 21 Jan 2026)',
    },
  },
  {
    id: 'vls-finance-buyback-2025',
    type: 'buyback',
    severity: 'high',
    title: 'VLS Finance — Buyback window live',
    description:
      'Tender offer window running 18–24 Dec 2025 with settlement to follow; live liquidity for existing holders.',
    source: 'DFM Archive',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
    isActioned: false,
    isRead: true,
    expectedTimeline: '30_days',
    estimatedLiquidity: 95,
    confidence: 88,
    metadata: {
      keyDates: ['Tender window 18–24 Dec 2025'],
      people: ['VLS Finance Limited (issuer)'],
      signalType: 'Buyback / tender offer',
      window: '0–30 days (by 21 Jan 2026)',
    },
  },
  {
    id: 'nureca-buyback-2025',
    type: 'buyback',
    severity: 'medium',
    title: 'Nureca — Buyback with verification date',
    description:
      'Tender offer open 18–24 Dec 2025; post-tender verification slated for 1 Jan 2026.',
    source: 'IPO Central',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6 hours ago
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 80,
    confidence: 84,
    metadata: {
      keyDates: ['Open 18 Dec 2025', 'Close 24 Dec 2025', 'Verification 1 Jan 2026'],
      people: ['Nureca', 'Public shareholders'],
      signalType: 'Buyback / tender offer',
      window: '0–30 days (by 21 Jan 2026)',
    },
  },
  {
    id: 'covidh-open-offer-2025',
    type: 'open_offer',
    severity: 'critical',
    title: 'Covidh Technologies — Open offer tendering',
    description:
      'Open offer tendering running 23 Dec 2025 to 6 Jan 2026; primary cash-out event under takeover regulations.',
    source: 'Dubai Financial Services Authority',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8 hours ago
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 220,
    confidence: 91,
    metadata: {
      keyDates: ['Tendering 23 Dec 2025 → 6 Jan 2026'],
      people: ['Promoter group references (e.g., Mr. Ganapa Narsi Reddy)'],
      signalType: 'Open offer / tendering period',
      window: '0–30 days (by 21 Jan 2026)',
    },
  },
  {
    id: 'avishkar-open-offer-2025',
    type: 'open_offer',
    severity: 'high',
    title: 'Avishkar Infra Realty — Open offer live',
    description:
      'Open offer window 23 Dec 2025 to 6 Jan 2026 after earlier allotment triggered SAST obligations.',
    source: 'Dubai Financial Services Authority',
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000), // 10 hours ago
    isActioned: false,
    isRead: true,
    expectedTimeline: '30_days',
    estimatedLiquidity: 140,
    confidence: 86,
    metadata: {
      keyDates: ['Tendering 23 Dec 2025 → 6 Jan 2026'],
      people: ['Acquirer + PACs'],
      signalType: 'Open offer / tendering period',
      window: '0–30 days (by 21 Jan 2026)',
    },
  },
  {
    id: 'mcx-stock-split-2026',
    type: 'stock_split',
    severity: 'medium',
    title: 'MCX — Stock split record date',
    description:
      'Record date set for 2 Jan 2026; split drives liquidity and trading volume around eligibility.',
    source: 'Gulf News',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12 hours ago
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_days',
    estimatedLiquidity: 65,
    confidence: 82,
    metadata: {
      keyDates: ['Record date 2 Jan 2026'],
      people: ['MCX shareholders'],
      signalType: 'Stock split',
      window: '0–30 days (by 21 Jan 2026)',
    },
  },
  {
    id: 'harmony-open-offer-2026',
    type: 'open_offer',
    severity: 'high',
    title: 'Harmony Capital Services — Open offer upcoming',
    description:
      'Tendering slated for 13–27 Jan 2026; cash-settlement mechanics relevant for post-offer liquidity.',
    source: 'Arabian Business',
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000), // 14 hours ago
    isActioned: false,
    isRead: false,
    expectedTimeline: '30_60_days',
    estimatedLiquidity: 110,
    confidence: 87,
    metadata: {
      keyDates: ['Tendering 13 Jan 2026 → 27 Jan 2026'],
      people: ['Dorni Vinimoy Pvt Ltd (acquirer)', 'Rajesh Ghosh (LOF signatory)'],
      signalType: 'Open offer / tendering period',
      window: '30–60 days (22 Jan → 20 Feb 2026)',
    },
  },
  {
    id: 'hul-demerger-2026',
    type: 'demerger',
    severity: 'medium',
    title: 'HUL — Ice cream business demerger listing expected',
    description:
      'Listing for the demerged ice cream unit expected Feb 2026; value unlock and rebalancing catalyst.',
    source: 'Gulf News',
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000), // 16 hours ago
    isActioned: false,
    isRead: true,
    expectedTimeline: '30_60_days',
    estimatedLiquidity: 300,
    confidence: 83,
    metadata: {
      keyDates: ['Listing expected Feb 2026'],
      people: ['HUL shareholders (record date already done)'],
      signalType: 'Demerger / value unlock',
      window: '30–60 days (22 Jan → 20 Feb 2026)',
    },
  },
  {
    id: 'airtel-rights-call-2026',
    type: 'rights_call',
    severity: 'high',
    title: 'Bharti Airtel — Partly-paid shares call',
    description:
      'Call money on partly-paid shares with record date 6 Feb 2026 and payment window 2–16 Mar 2026.',
    source: 'Saxo Bank',
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000), // 18 hours ago
    isActioned: false,
    isRead: false,
    expectedTimeline: '60_90_days',
    estimatedLiquidity: 275,
    confidence: 89,
    metadata: {
      keyDates: ['Record date 6 Feb 2026', 'Payment window 2–16 Mar 2026'],
      people: ['Holders of partly paid-up shares'],
      signalType: 'Rights/partly-paid call',
      window: '60–90 days (21 Feb → 21 Mar 2026)',
    },
  },
  {
    id: 'covidh-open-offer-settlement-2026',
    type: 'open_offer',
    severity: 'medium',
    title: 'Covidh Technologies — Open offer settlement milestone',
    description:
      'Settlement completion milestone shown as 20 Jan 2026; downstream liquidity depends on acceptance levels.',
    source: 'Dubai Financial Services Authority',
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000), // 20 hours ago
    isActioned: false,
    isRead: false,
    expectedTimeline: '60_90_days',
    estimatedLiquidity: 90,
    confidence: 80,
    metadata: {
      keyDates: ['Settlement milestone 20 Jan 2026'],
      people: ['Offer participants'],
      signalType: 'Open offer settlement',
      window: '60–90 days (21 Feb → 21 Mar 2026)',
    },
  },
];
