/**
 * @file compliance-mock-data.ts
 * @description Mock data for compliance features (demo purposes only)
 * @module lib/mock-data
 */

import type {
  ComplianceTerm,
  ClientComplianceStatus,
  ComplianceAlert,
  MonitoredTransaction,
  RegulatoryReport,
  ComplianceGapSummary,
  ShariahDriftAlert,
  ProductShariahInfo,
  ComplianceDashboardMetrics,
} from '@/types/compliance.types';

// ============================================
// SHARIAH COMPLIANCE MOCK DATA
// ============================================

export const mockProductShariahInfo: ProductShariahInfo[] = [
  {
    productId: 'prod-001',
    shariahStatus: 'COMPLIANT',
    certifiedBy: 'AAOIFI',
    certificationDate: new Date('2024-01-15'),
    certificationExpiry: new Date('2025-01-15'),
    certificateUrl: '/docs/shariah-cert-001.pdf',
    screeningCriteria: {
      prohibitedActivitiesCheck: true,
      debtToAssetRatio: 0.30,
      interestIncomeRatio: 0.05,
      receivablesRatio: 0.45,
    },
    lastScreenedAt: new Date('2024-11-01'),
    updatedBy: 'admin@kairos.mu',
    updatedAt: new Date('2024-11-01'),
  },
  {
    productId: 'prod-002',
    shariahStatus: 'NON_COMPLIANT',
    updatedBy: 'admin@kairos.mu',
    updatedAt: new Date('2024-10-15'),
  },
  {
    productId: 'prod-003',
    shariahStatus: 'PENDING_REVIEW',
    updatedBy: 'admin@kairos.mu',
    updatedAt: new Date('2024-12-01'),
  },
];

export const mockShariahDriftAlerts: ShariahDriftAlert[] = [
  {
    id: 'alert-sh-001',
    clientId: 'client-001',
    portfolioId: 'port-001',
    alertType: 'NEW_NON_COMPLIANT',
    severity: 'HIGH',
    affectedHoldings: [
      {
        productId: 'prod-002',
        productName: 'Conventional Bond Fund',
        holdingValue: 150000,
        holdingPercentage: 12.5,
        reason: 'Contains interest-based instruments',
      },
    ],
    status: 'PENDING',
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2025-01-01'),
  },
  {
    id: 'alert-sh-002',
    clientId: 'client-002',
    portfolioId: 'port-002',
    alertType: 'CERTIFICATION_EXPIRED',
    severity: 'MEDIUM',
    affectedHoldings: [
      {
        productId: 'prod-004',
        productName: 'Islamic Equity Fund',
        holdingValue: 75000,
        holdingPercentage: 8.0,
        reason: 'Shariah certification expired',
      },
    ],
    status: 'ACKNOWLEDGED',
    acknowledgedBy: 'rm@kairos.mu',
    acknowledgedAt: new Date('2025-01-02'),
    createdAt: new Date('2024-12-28'),
    updatedAt: new Date('2025-01-02'),
  },
];

// ============================================
// GCC REGULATORY COMPLIANCE MOCK DATA
// ============================================

export const mockMonitoredTransactions: MonitoredTransaction[] = [
  {
    id: 'txn-001',
    clientId: 'client-001',
    portfolioId: 'port-001',
    transactionType: 'WITHDRAWAL',
    amount: 250000,
    currency: 'SAR',
    isCrossBorder: false,
    complianceStatus: 'FLAGGED',
    flagReasons: ['Exceeds single transaction threshold', 'High-risk client'],
    clientRiskRating: 'HIGH',
    enhancedDueDiligence: true,
    politicallyExposed: false,
    transactionDate: new Date('2025-01-02T10:30:00'),
    monitoredAt: new Date('2025-01-02T10:31:00'),
    updatedAt: new Date('2025-01-02T10:31:00'),
  },
  {
    id: 'txn-002',
    clientId: 'client-003',
    portfolioId: 'port-003',
    transactionType: 'TRANSFER',
    amount: 500000,
    currency: 'USD',
    isCrossBorder: true,
    sourceJurisdiction: 'United Arab Emirates',
    destinationJurisdiction: 'United States',
    complianceStatus: 'UNDER_REVIEW',
    flagReasons: ['Cross-border transaction', 'PEP client'],
    clientRiskRating: 'MEDIUM',
    enhancedDueDiligence: true,
    politicallyExposed: true,
    reviewedBy: 'compliance@kairos.mu',
    reviewedAt: new Date('2025-01-02T14:00:00'),
    reviewNotes: 'Requested additional documentation',
    transactionDate: new Date('2025-01-02T12:00:00'),
    monitoredAt: new Date('2025-01-02T12:05:00'),
    updatedAt: new Date('2025-01-02T14:00:00'),
  },
  {
    id: 'txn-003',
    clientId: 'client-002',
    portfolioId: 'port-002',
    transactionType: 'BUY',
    amount: 125000,
    currency: 'SAR',
    isCrossBorder: false,
    complianceStatus: 'COMPLIANT',
    flagReasons: [],
    clientRiskRating: 'LOW',
    enhancedDueDiligence: false,
    politicallyExposed: false,
    transactionDate: new Date('2025-01-02T09:15:00'),
    monitoredAt: new Date('2025-01-02T09:16:00'),
    updatedAt: new Date('2025-01-02T09:16:00'),
  },
];

export const mockComplianceAlerts: ComplianceAlert[] = [
  {
    id: 'alert-001',
    alertType: 'THRESHOLD_EXCEEDED',
    severity: 'CRITICAL',
    title: 'Large Transaction Threshold Exceeded',
    description: 'Transaction of SAR 250,000 exceeds SAMA single transaction limit',
    relatedEntityType: 'TRANSACTION',
    relatedEntityId: 'txn-001',
    authority: 'SAMA',
    status: 'ACTIVE',
    assignedTo: 'compliance@kairos.mu',
    triggeredAt: new Date('2025-01-02T10:31:00'),
    dueDate: new Date('2025-01-04T10:31:00'),
  },
  {
    id: 'alert-002',
    alertType: 'CROSS_BORDER_FLAGGED',
    severity: 'HIGH',
    title: 'Cross-Border Transaction Requires Review',
    description: 'USD 500,000 transfer from UAE to US requires enhanced documentation',
    relatedEntityType: 'TRANSACTION',
    relatedEntityId: 'txn-002',
    authority: 'DIFC',
    status: 'IN_PROGRESS',
    assignedTo: 'compliance@kairos.mu',
    triggeredAt: new Date('2025-01-02T12:05:00'),
    acknowledgedAt: new Date('2025-01-02T13:00:00'),
    dueDate: new Date('2025-01-05T12:05:00'),
  },
  {
    id: 'alert-003',
    alertType: 'REGULATORY_DEADLINE',
    severity: 'MEDIUM',
    title: 'Quarterly AML Report Due Soon',
    description: 'Q4 2024 AML monitoring report due to SAMA in 5 days',
    relatedEntityType: 'REPORT',
    relatedEntityId: 'report-q4-2024',
    authority: 'SAMA',
    status: 'ACTIVE',
    assignedTo: 'compliance@kairos.mu',
    triggeredAt: new Date('2024-12-28T09:00:00'),
    dueDate: new Date('2025-01-07T23:59:00'),
  },
];

export const mockRegulatoryReports: RegulatoryReport[] = [
  {
    id: 'report-q4-2024',
    authority: 'SAMA',
    reportType: 'AML_MONITORING',
    reportingPeriod: {
      startDate: new Date('2024-10-01'),
      endDate: new Date('2024-12-31'),
    },
    summary: {
      totalTransactions: 1247,
      totalVolume: 125600000,
      flaggedTransactions: 34,
      suspiciousActivities: 3,
      crossBorderCount: 87,
      highRiskClients: 12,
      pepClients: 5,
    },
    transactions: mockMonitoredTransactions,
    suspiciousActivities: [],
    crossBorderTransactions: [],
    status: 'PENDING_REVIEW',
    generatedBy: 'system@kairos.mu',
    generatedAt: new Date('2025-01-01T08:00:00'),
    exportFormat: 'PDF',
    auditTrailId: 'audit-001',
  },
];

// ============================================
// COMPLIANCE TAB MOCK DATA
// ============================================

export const mockComplianceTerms: ComplianceTerm[] = [
  {
    id: 'term-001',
    name: 'KYC Enhanced Due Diligence',
    description: 'Enhanced due diligence requirements for high-risk clients',
    jurisdiction: 'SAUDI_ARABIA',
    authority: 'SAMA',
    effectiveDate: new Date('2024-01-01'),
    mandatory: true,
    category: 'KYC',
    severity: 'CRITICAL',
    version: '2.1',
    documentationIds: ['doc-001', 'doc-002'],
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'term-002',
    name: 'Cross-Border Transaction Reporting',
    description: 'All transactions exceeding USD 10,000 must be reported within 24 hours',
    jurisdiction: 'UAE',
    authority: 'DIFC',
    effectiveDate: new Date('2024-03-01'),
    mandatory: true,
    category: 'CROSS_BORDER',
    severity: 'HIGH',
    version: '1.0',
    documentationIds: ['doc-003'],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'term-003',
    name: 'Shariah Compliance Certification',
    description: 'All Islamic finance products must maintain valid Shariah certification',
    jurisdiction: 'SAUDI_ARABIA',
    authority: 'SAMA',
    effectiveDate: new Date('2023-06-01'),
    mandatory: true,
    category: 'SHARIAH',
    severity: 'CRITICAL',
    version: '1.5',
    documentationIds: ['doc-004', 'doc-005'],
    createdAt: new Date('2023-05-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'term-004',
    name: 'Annual AML Training',
    description: 'All staff must complete annual AML training and certification',
    jurisdiction: 'UAE',
    authority: 'ADGM',
    effectiveDate: new Date('2024-01-01'),
    mandatory: true,
    category: 'AML',
    severity: 'MEDIUM',
    version: '3.0',
    documentationIds: ['doc-006'],
    createdAt: new Date('2023-11-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockClientComplianceStatuses: ClientComplianceStatus[] = [
  {
    clientId: 'client-001',
    clientName: 'Abdullah Al-Rashid',
    overallScore: 85,
    requirements: [
      {
        id: 'req-001',
        termId: 'term-001',
        termName: 'KYC Enhanced Due Diligence',
        category: 'KYC',
        status: 'MET',
        completedDate: new Date('2024-06-15'),
        evidence: [
          {
            id: 'ev-001',
            requirementId: 'req-001',
            fileName: 'passport-scan.pdf',
            fileUrl: '/docs/passport-scan.pdf',
            uploadedBy: 'rm@kairos.mu',
            uploadedAt: new Date('2024-06-15'),
            verified: true,
            verifiedBy: 'compliance@kairos.mu',
            verifiedAt: new Date('2024-06-16'),
          },
        ],
      },
      {
        id: 'req-002',
        termId: 'term-003',
        termName: 'Shariah Compliance Certification',
        category: 'SHARIAH',
        status: 'PENDING',
        dueDate: new Date('2025-01-15'),
        evidence: [],
        notes: 'Awaiting updated certification from Shariah board',
      },
    ],
    missingCount: 1,
    upcomingDeadlines: [
      {
        requirementId: 'req-002',
        requirementName: 'Shariah Compliance Certification',
        dueDate: new Date('2025-01-15'),
        severity: 'CRITICAL',
        daysRemaining: 13,
        status: 'DUE_SOON',
      },
    ],
    lastReviewDate: new Date('2024-12-15'),
    nextReviewDate: new Date('2025-06-15'),
    assignedOfficer: 'compliance@kairos.mu',
  },
  {
    clientId: 'client-002',
    clientName: 'Fatima Al-Kuwari',
    overallScore: 95,
    requirements: [
      {
        id: 'req-003',
        termId: 'term-001',
        termName: 'KYC Enhanced Due Diligence',
        category: 'KYC',
        status: 'MET',
        completedDate: new Date('2024-08-20'),
        evidence: [],
      },
      {
        id: 'req-004',
        termId: 'term-003',
        termName: 'Shariah Compliance Certification',
        category: 'SHARIAH',
        status: 'MET',
        completedDate: new Date('2024-09-10'),
        evidence: [],
      },
    ],
    missingCount: 0,
    upcomingDeadlines: [],
    lastReviewDate: new Date('2024-11-20'),
    nextReviewDate: new Date('2025-05-20'),
    assignedOfficer: 'compliance@kairos.mu',
  },
  {
    clientId: 'client-003',
    clientName: 'Mohammed Al-Suwaidi',
    overallScore: 65,
    requirements: [
      {
        id: 'req-005',
        termId: 'term-001',
        termName: 'KYC Enhanced Due Diligence',
        category: 'KYC',
        status: 'OVERDUE',
        dueDate: new Date('2024-12-01'),
        evidence: [],
        notes: 'Client has not responded to document requests',
      },
      {
        id: 'req-006',
        termId: 'term-002',
        termName: 'Cross-Border Transaction Reporting',
        category: 'CROSS_BORDER',
        status: 'PENDING',
        dueDate: new Date('2025-01-20'),
        evidence: [],
      },
    ],
    missingCount: 2,
    upcomingDeadlines: [
      {
        requirementId: 'req-005',
        requirementName: 'KYC Enhanced Due Diligence',
        dueDate: new Date('2024-12-01'),
        severity: 'CRITICAL',
        daysRemaining: -32,
        status: 'OVERDUE',
      },
      {
        requirementId: 'req-006',
        requirementName: 'Cross-Border Transaction Reporting',
        dueDate: new Date('2025-01-20'),
        severity: 'HIGH',
        daysRemaining: 18,
        status: 'UPCOMING',
      },
    ],
    lastReviewDate: new Date('2024-10-15'),
    nextReviewDate: new Date('2025-04-15'),
    assignedOfficer: 'compliance@kairos.mu',
  },
];

export const mockComplianceGapSummary: ComplianceGapSummary = {
  totalClients: 245,
  clientsWithGaps: 89,
  totalGaps: 134,
  gapsByCategory: {
    AML: 23,
    KYC: 45,
    CROSS_BORDER: 18,
    SHARIAH: 31,
    REPORTING: 12,
    LICENSING: 5,
  },
  gapsBySeverity: {
    CRITICAL: 34,
    HIGH: 52,
    MEDIUM: 38,
    LOW: 10,
  },
  criticalGaps: [
    {
      clientId: 'client-003',
      clientName: 'Mohammed Al-Suwaidi',
      requirementId: 'req-005',
      requirementName: 'KYC Enhanced Due Diligence',
      category: 'KYC',
      severity: 'CRITICAL',
      daysOverdue: 32,
      recommendation: 'Suspend trading activity until compliance documentation received',
    },
    {
      clientId: 'client-015',
      clientName: 'Ahmed Al-Dosari',
      requirementId: 'req-087',
      requirementName: 'PEP Declaration Update',
      category: 'KYC',
      severity: 'CRITICAL',
      daysOverdue: 15,
      recommendation: 'Escalate to senior compliance officer',
    },
  ],
};

export const mockComplianceDashboardMetrics: ComplianceDashboardMetrics = {
  totalClients: 245,
  compliantClients: 156,
  activeAlerts: 23,
  pendingReports: 4,
  flaggedTransactions: 34,
  crossBorderTransactions: 87,
  overallComplianceScore: 78,
  trendDirection: 'UP',
};
